import { useState, type FormEvent } from 'react'
import { ArrowUpRight, ArrowRight, Menu, X, ShoppingBag, Workflow, Target, MousePointer2, Plus, MessageCircle } from 'lucide-react'
import { config, track } from './config'

const nav = [['Home', 'home'], ['About', 'about'], ['Services', 'services'], ['Our Approach', 'approach'], ['Work', 'work'], ['Insights', 'insights'], ['Contact', 'contact']]
function Brand() { return <a className="brand" href="#home" aria-label="Chazon Digital Ventures home"><span className="brand-mark">c<span>↗</span></span><span>CHAZON<small>DIGITAL VENTURES</small></span></a> }
function Button({ children, href = '#contact', secondary = false }: { children: React.ReactNode; href?: string; secondary?: boolean }) { return <a className={`button ${secondary ? 'secondary' : ''}`} href={href}>{children}<ArrowUpRight size={18}/></a> }
function Label({ children, light = false }: { children: React.ReactNode; light?: boolean }) { return <div className={`eyebrow ${light ? 'light' : ''}`}><span/>{children}</div> }
function Navbar() {
  const [open, setOpen] = useState(false)
  return <header className="header"><div className="container nav-wrap"><Brand/><nav className={open ? 'nav open' : 'nav'} aria-label="Main navigation">{nav.map(([name, id]) => <a key={id} href={`#${id}`} onClick={() => setOpen(false)}>{name}</a>)}</nav><a className="header-cta" href="#contact">LET’S TALK <ArrowUpRight size={15}/></a><button className="menu-toggle" aria-label={open ? 'Close navigation' : 'Open navigation'} aria-expanded={open} onClick={() => setOpen(!open)}>{open ? <X/> : <Menu/>}</button></div></header>
}

// Fig. 01 — strategy feeds a loop of digital stages; growth leaves the loop as the output.
const engineStages: [string, string, number, number, 'middle' | 'end'][] = [['01', 'Website', 125, 170, 'middle'], ['02', 'Traffic', 202, 170, 'middle'], ['03', 'Leads', 278, 170, 'middle'], ['04', 'Conversion', 355, 170, 'middle'], ['05', 'Automation', 440, 255, 'end'], ['06', 'Retention', 290, 340, 'middle']]
function RevenueEngine() {
  const track = 'M125 170H355A85 85 0 0 1 355 340H125A85 85 0 0 1 125 170Z'
  return <figure className="engine">
    <svg viewBox="0 0 480 460" role="img" aria-labelledby="engine-title">
      <title id="engine-title">The digital revenue engine: strategy directs website, traffic, leads, conversion, automation and retention, which work as one loop and produce growth.</title>
      <text className="eng-eyebrow" x="240" y="22" textAnchor="middle">SETS THE DIRECTION</text>
      <text className="eng-strategy" x="240" y="54" textAnchor="middle">Strategy</text>
      {engineStages.slice(0, 4).map(([, , x, y]) => <path key={x} className="eng-fan" d={`M240 70C240 120 ${x} 115 ${x} ${y}`}/>)}
      <path className="eng-track" d={track}/>
      <path className="eng-flow" d={track}/>
      <path className="eng-output" d="M180 340V372Q180 404 212 404H292L322 395L350 398L384 380L414 383L450 352"/>
      <path className="eng-output" d="M437 352H450V365"/>
      {engineStages.map(([n, name, x, y, anchor]) => { const tx = anchor === 'end' ? x - 20 : x; const ty = y === 340 ? y - 34 : y === 255 ? y - 10 : y + 28; return <g key={n}>
        <circle className={n === '04' ? 'eng-node key' : 'eng-node'} cx={x} cy={y} r={n === '04' ? 7 : 5.5}/>
        <text className="eng-num" x={tx} y={ty} textAnchor={anchor}>{n}</text>
        <text className="eng-label" x={tx} y={ty + 18} textAnchor={anchor}>{name}</text>
      </g> })}
      <circle className="eng-node key" cx="180" cy="340" r="5.5"/>
      <text className="eng-meta" x="56" y="259">REPEAT CUSTOMERS</text>
      <g className="eng-bars">{[6, 9, 8, 13, 17, 15, 23].map((h, i) => <rect key={i} className={i === 6 ? 'last' : ''} x={211 + i * 9} y={268 - h} width="5" height={h}/>)}</g>
      <text className="eng-meta" x="240" y="288" textAnchor="middle">EVERY STAGE MEASURED</text>
      <text className="eng-num" x="212" y="428">07</text>
      <text className="eng-growth" x="236" y="432">Growth</text>
    </svg>
    <figcaption><span>Fig. 01</span>The digital revenue engine — separate activities, one connected system.</figcaption>
  </figure>
}
function Hero() { return <section id="home" className="hero"><div className="container"><Label>YOUR DIGITAL REVENUE & GROWTH PARTNER</Label><h1>Turn your digital presence into a <em>revenue engine.</em></h1><div className="hero-grid"><div className="hero-copy"><p>Chazon Digital Ventures helps businesses build, optimise and scale their digital revenue channels through strategy, technology, marketing and automation.</p><div className="button-row"><Button>Let’s Talk</Button><Button href="#services" secondary>Explore Our Services</Button></div><ul className="hero-foot"><li>Business-first thinking</li><li>Measurable direction</li><li>Connected execution</li></ul></div><RevenueEngine/></div></div></section> }

const problems = [['A website,', 'but limited enquiries.'], ['Social media,', 'but poor conversion.'], ['Advertising,', 'but unclear ROI.'], ['Leads,', 'but poor follow-up.'], ['Processes', 'still run by hand.'], ['Digital platforms', 'that don’t talk to each other.']]
function ProblemSection() { return <section className="section problem"><div className="container problem-grid"><div className="problem-intro"><Label>THE DISCONNECT</Label><h2>Having a digital presence is not the same as having a digital <em>growth engine.</em></h2><p>Sound familiar? You have the pieces. They’re just not working together to grow your business.</p></div><div><ol className="problem-list">{problems.map(([have, but], i) => <li key={have}><span>0{i + 1}</span><p>{have} <strong>{but}</strong></p></li>)}</ol><div className="problem-end"><p>Disconnected platforms. Missed opportunities. No clear picture of what drives revenue.</p><a href="#value">That’s where Chazon comes in <ArrowRight size={18}/></a></div></div></div></section> }

function ValueProposition() { const items = [['Strategy', 'Understand your business, customers and competition. Find the real revenue opportunity.'], ['Execution', 'Build and activate the platforms, campaigns and customer journeys that move your business forward.'], ['Optimisation', 'Measure what matters. Learn from performance. Keep improving the system.']]; return <section id="value" className="section value"><div className="container"><div className="value-head"><Label>THE CONNECTED ADVANTAGE</Label><h2>One partner. <span className="muted">A connected digital ecosystem.</span></h2><p>From your first touchpoint to your next repeat customer.</p></div><div className="value-rows">{items.map(([title, text], i) => <div className="value-row" key={title}><h3>{i > 0 && <span>+</span>}{title}</h3><p>{text}</p></div>)}</div><p className="value-loop"><span/>…then back to strategy, with better data each time.</p></div></section> }

const services = [
  { title: 'Digital Foundation', subtitle: 'Build the right starting point.', text: 'Digital platforms designed to turn first impressions into meaningful business opportunities.', items: ['Website Development', 'E-commerce Development', 'Landing Pages', 'Google Business Profile', 'Digital Platform Setup', 'UI/UX & Conversion Optimisation'] },
  { title: 'Digital Growth', subtitle: 'Reach the people who matter.', text: 'Connect your business with the right audience through focused, purposeful digital marketing.', items: ['Performance Marketing', 'Google Ads', 'Meta Ads', 'Social Media Marketing', 'SEO', 'Lead Generation', 'Content Strategy', 'Digital Campaigns'] },
  { title: 'Revenue & Commerce', subtitle: 'Turn opportunity into revenue.', text: 'Join up the customer journey, remove friction and create stronger digital revenue channels.', items: ['Digital Revenue Strategy', 'E-commerce Strategy', 'Marketplace Strategy', 'Conversion Optimisation', 'Customer Journey Mapping', 'Pricing & Merchandising', 'Digital Commerce Consulting'] },
  { title: 'Automation & Retention', subtitle: 'Make every connection count.', text: 'Build smarter follow-ups and connected experiences that keep customers coming back.', items: ['WhatsApp Business Solutions', 'Lead Follow-up Automation', 'Customer Communication', 'Marketing Automation', 'CRM Workflows', 'AI-powered Customer Support', 'Repeat Purchase / Retention Systems'] },
]
function ServicePillars() { return <section id="services" className="section services"><div className="container"><div className="section-heading split"><div><Label>OUR CAPABILITIES</Label><h2>Four pillars.<br/>One growth objective.</h2></div><p>Everything your digital business needs. Connected by strategy. Focused on revenue.</p></div><div className="service-list">{services.map(({ title, subtitle, text, items }, i) => <article className="service-card" key={title}><span className="service-num">0{i + 1}</span><div className="service-title"><h3>{title}</h3><strong>{subtitle}</strong></div><p>{text}</p><details><summary>{items.length} capabilities <Plus size={18}/></summary><ul>{items.map(item => <li key={item}>{item}</li>)}</ul></details></article>)}</div></div></section> }

const chazonQuestions = ['What are you trying to achieve?', 'Where are your customers?', 'What digital journey will move them toward conversion?', 'Which platforms and channels should we use?', 'How do we measure the commercial outcome?']
function DifferenceSection() { return <section className="difference section"><div className="container"><Label light>THE CHAZON DIFFERENCE</Label><h2>We don’t start with the channel.<br/> We start with the <em>business objective.</em></h2><figure className="framework"><div className="channel-first"><span className="framework-label">CHANNEL-FIRST <small>The usual conversation</small></span><ul>{['“You need Instagram.”', '“You need Google Ads.”', '“You need a website.”'].map(x => <li key={x}>{x}</li>)}</ul><p>Starts with a tool. Hopes for a result.</p></div><div className="framework-vs" aria-hidden="true"><span>vs</span></div><div className="business-first"><span className="framework-label orange">BUSINESS-FIRST <small>The Chazon conversation</small></span><ol>{chazonQuestions.map((q, i) => <li key={q}><span>0{i + 1}</span>{q}</li>)}</ol><p>Starts with the result. Chooses the tools to match.</p></div><figcaption><span>Fig. 02</span>Two ways to begin a digital project.</figcaption></figure><div className="difference-foot"><p>A platform is a tool. Growth needs a plan. We connect every digital decision to what your business actually needs to achieve.</p><Button href="#approach">See How We Work</Button></div></div></section> }

const steps = [['Discover', 'Your business, audience, digital assets and the challenges holding you back.'], ['Strategise', 'A growth roadmap with the right channels, customer journey and clear KPIs.'], ['Build', 'Create or optimise the platforms and digital assets your strategy needs.'], ['Execute', 'Activate campaigns, content, advertising and customer automation.'], ['Measure', 'Track traffic, leads, conversions and meaningful revenue indicators.'], ['Optimise', 'Use what the data tells us to continuously improve your digital ecosystem.']]
function ProcessSection() { return <section id="approach" className="section process"><div className="container"><div className="section-heading split"><div><Label>OUR APPROACH</Label><h2>Purpose at every step.<br/>Progress at every stage.</h2></div><p>A structured approach to digital growth. No random activity. No disconnected execution.</p></div><figure className="process-figure"><ol className="process-steps">{steps.map(([title, text], i) => <li key={title} style={{ '--i': i } as React.CSSProperties}><span className="process-number">0{i + 1}{i === steps.length - 1 && <ArrowUpRight size={18}/>}</span><h3>{title}</h3><p>{text}</p></li>)}</ol><figcaption><span>Fig. 03</span>Each stage builds on the last.</figcaption></figure></div></section> }

function AuditSection() { return <section className="audit"><div className="container audit-grid"><div><Label>FIND YOUR NEXT GROWTH OPPORTUNITY</Label><h2>How hard is your digital presence working for your business?</h2><p>A Digital Growth Audit looks at where the pieces can work better together.</p><Button href="#contact">Get a Digital Growth Audit</Button></div><ul className="audit-list" aria-label="What the audit covers">{['Website', 'SEO', 'Google visibility', 'Social media', 'Paid advertising', 'Conversion journey', 'Lead handling'].map((x, i) => <li key={x}><span>{String(i + 1).padStart(2, '0')}</span>{x}</li>)}</ul></div></section> }

function SelectedWork() { return <section id="work" className="section work"><div className="container"><div className="section-heading split"><div><Label>SELECTED WORK</Label><h2>Business challenges.<br/>Connected solutions.</h2></div><p>Good work deserves a clear story. Our detailed project stories are coming soon.</p></div><div className="work-grid">{[['Digital commerce', 'From storefront to customer journey.', 'commerce'], ['Lead generation', 'From first click to meaningful enquiry.', 'leads']].map(([category, title, style]) => <article className="work-card" key={title}><div className={`work-art ${style}`} aria-hidden="true">{style === 'commerce' ? <><div className="mock-browser"><div className="browser-dots">••• <span>COMMERCE / CONNECTED</span></div><div className="mock-store"><div><small>DISCOVER. CONNECT. CONVERT.</small><strong>A better<br/>way to buy.</strong><span className="mock-btn">Explore collection ↗</span></div><div className="product-shape"/></div><div className="mock-products"><span/><span/><span/></div></div><div className="floating-tag"><ShoppingBag size={16}/> Seamless commerce</div></> : <><div className="journey-block"><Target size={23}/><span>Attract</span></div><span className="journey-dash"/><div className="journey-block active"><MousePointer2 size={23}/><span>Convert</span></div><span className="journey-dash"/><div className="journey-block"><MessageCircle size={23}/><span>Connect</span></div><div className="floating-tag"><Workflow size={16}/> A connected customer journey</div></>}<span className="placeholder-badge">Placeholder — case study to be published</span></div><div className="work-body"><span className="eyebrow-text">{category} / ILLUSTRATIVE FRAMEWORK</span><h3>{title}</h3><details><summary>Preview case study structure <Plus size={17}/></summary><p>Project story awaiting publication. This illustration is a framework, not a client project or a claim of results.</p><dl>{['Client / project', 'Business challenge', 'Chazon’s role', 'Strategy', 'Execution & deliverables', 'Outcome / current status'].map(label => <div key={label}><dt>{label}</dt><dd>To be added with verified project details.</dd></div>)}</dl></details></div></article>)}</div></div></section> }
const industries = ['D2C & E-commerce', 'Retail', 'Hospitality', 'Travel & Tourism', 'Professional Services', 'Healthcare & Wellness', 'Manufacturing', 'B2B', 'Start-ups & Entrepreneurs']
function IndustriesSection() { const [selected, setSelected] = useState('D2C & E-commerce'); const descriptions: Record<string, string> = { 'D2C & E-commerce': 'Connect discovery, shopping and retention to build a stronger digital commerce journey.', Retail: 'Connect your local visibility and online presence to create a clearer path to purchase.', Hospitality: 'Help guests discover your business, explore the experience and make an enquiry or booking.', 'Travel & Tourism': 'Bring inspiration, enquiry and follow-up together in one considered customer journey.', 'Professional Services': 'Make your expertise easy to understand and help the right prospects take the next step.', 'Healthcare & Wellness': 'Build clear, accessible digital experiences that help people find your services and enquire.', Manufacturing: 'Translate your capabilities into a digital presence that supports trade enquiries and commerce.', B2B: 'Support longer buying journeys with relevant content, qualified enquiries and consistent follow-up.', 'Start-ups & Entrepreneurs': 'Prioritise the right digital foundations and channels for your next stage of business.' }; return <section className="section industries"><div className="container industry-grid"><div><Label>BUILT AROUND YOUR BUSINESS</Label><h2>Different industries.<br/>The same ambition.</h2><p>Digital growth shaped around your customers, your market and your commercial goals.</p></div><div><div className="industry-chips">{industries.map(x => <button key={x} aria-pressed={selected === x} onClick={() => setSelected(x)} className={selected === x ? 'selected' : ''}>{x}<ArrowUpRight size={14}/></button>)}</div><p className="industry-description" aria-live="polite">{descriptions[selected]}</p></div></div></section> }
const principles = [['Business-first thinking', 'Your objectives set the direction. The channels follow.'], ['Strategy-led execution', 'Every activity connects to a defined objective and KPI.'], ['Integrated digital thinking', 'Your website, search, social, advertising and automation work together.'], ['Practical execution', 'Consultative thinking meets hands-on implementation.'], ['Data-led optimisation', 'Real performance informs the next decision.'], ['Flexible engagement', 'A specific project, ongoing execution or an extended growth partnership.']]
function WhyChazon() { return <section className="section why"><div className="container"><Label>WHY CHAZON</Label><h2>Your business doesn’t need more digital activity. <span className="muted">It needs the right digital activity.</span></h2><div className="principles">{principles.map(([title, text], i) => <article key={title}><span>0{i + 1}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section> }
function FounderSection() { return <section id="about" className="section about"><div className="container about-grid"><div className="founder-placeholder" role="img" aria-label="Placeholder for a portrait of Binny Rogin"><span className="portrait-label">PORTRAIT PLACEHOLDER</span><div className="monogram">br<span>↗</span></div><span className="portrait-name">BINNY ROGIN</span><small>Replace with an approved professional photo</small></div><div><Label>MEET CHAZON</Label><h2>A business perspective.<br/>A digital mindset.</h2><p className="large-copy">Chazon brings strategy and execution together to help businesses build, optimise and grow their digital revenue channels.</p><p>Led by Binny Rogin, the practice brings together experience across marketing, media planning, digital platforms, website development, performance marketing, social media and digital commerce.</p><p>The focus is practical: understand the business, connect the right digital capabilities and keep improving the path to revenue.</p><a className="text-link" href="#contact">Know Chazon. Start a conversation. <ArrowUpRight size={18}/></a></div></div></section> }
function InsightsSection() { const topics = [['Digital revenue', 'Why traffic doesn’t always mean revenue', 'A closer look at the gap between attracting visitors and helping them become customers.'], ['Digital commerce', 'Your customer journey is your growth opportunity', 'Exploring the moments between discovery, purchase and a customer coming back.'], ['Automation', 'Better follow-ups. Fewer missed opportunities.', 'How thoughtful lead handling can connect the first enquiry to the next conversation.']]; return <section id="insights" className="section insights"><div className="container"><div className="section-heading split"><div><Label>THE GROWTH PERSPECTIVE</Label><h2>Clear thinking.<br/>Practical digital insights.</h2></div><p>Ideas for business owners building what’s next. Our editorial collection is in development.</p></div><div className="insight-list">{topics.map(([cat, title, desc]) => <article key={cat}><span className="eyebrow-text">{cat}</span><h3>{title}</h3><p>{desc}</p><span className="coming-soon">Coming soon</span></article>)}</div><div className="editorial-note">ALSO ON THE HORIZON <span>Performance Marketing</span><span>Entrepreneur’s Digital Playbook</span></div></div></section> }
function WhatsApp({ mobile = false }: { mobile?: boolean }) { const valid = /^\d{7,15}$/.test(config.whatsapp); return <a className={mobile ? 'mobile-whatsapp' : 'whatsapp-link'} href={valid ? `https://wa.me/${config.whatsapp}` : '#contact'} onClick={() => track(valid ? 'whatsapp_click' : 'contact_click', { location: mobile ? 'mobile' : 'contact' })} {...(valid ? { target: '_blank', rel: 'noopener noreferrer' } : {})}><MessageCircle size={19}/>{valid ? 'WhatsApp Us' : mobile ? 'Let’s Talk' : 'WhatsApp — details coming soon'}{!mobile && <ArrowUpRight size={16}/>}</a> }
function ContactForm() {
  const [status, setStatus] = useState(''); const [busy, setBusy] = useState(false)
  async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); const form = e.currentTarget; const data = Object.fromEntries(new FormData(form)); if (data.company_url) return; if (!config.enquiryEndpoint) { setStatus('Online enquiries are not connected yet. Your details have not been sent. Please use the contact email when available.'); return } setBusy(true); setStatus(''); try { const response = await fetch(config.enquiryEndpoint, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); if (!response.ok) throw new Error('Submission failed'); setStatus('Thank you. Your enquiry has been received. We look forward to learning about your business.'); track('form_submission', { form: 'growth_enquiry' }); form.reset() } catch { setStatus('Your enquiry could not be sent. Please try again or use the contact email.'); } finally { setBusy(false) } }
  return <form onSubmit={submit} className="contact-form"><div className="form-grid"><label>Name <span>*</span><input name="name" autoComplete="name" required maxLength={100} placeholder="Your name"/></label><label>Business name <span>*</span><input name="business" autoComplete="organization" required maxLength={150} placeholder="Your business"/></label><label>Email <span>*</span><input type="email" name="email" autoComplete="email" required placeholder="you@business.com"/></label><label>Phone <span>*</span><input type="tel" name="phone" autoComplete="tel" required pattern="[+0-9\(\) .\-]{7,20}" title="Enter a phone number with 7–20 characters." placeholder="Your phone number"/></label><label>Website / Instagram<input name="website" placeholder="Website or @handle" maxLength={200}/></label><label>Business category<select name="category" defaultValue="" required><option value="" disabled>Select your industry</option>{industries.map(x => <option key={x}>{x}</option>)}<option>Other</option></select></label><label>What do you need help with? <span>*</span><select name="service" defaultValue="" required><option value="" disabled>Select a service</option>{['Digital Growth Audit', 'Website', 'Digital Marketing', 'Performance Marketing', 'Social Media', 'E-commerce', 'Business Automation', 'Digital Revenue Strategy', 'Other'].map(x => <option key={x}>{x}</option>)}</select></label><label>Monthly marketing budget <small>(optional)</small><select name="budget" defaultValue=""><option value="">Select a range</option><option>Under ₹25,000</option><option>₹25,000–₹50,000</option><option>₹50,000–₹1,00,000</option><option>₹1,00,000+</option><option>Let’s discuss</option></select></label><label className="full">Tell us about your business<textarea name="message" rows={3} maxLength={3000} placeholder="What would you like to achieve?"/></label></div><div className="honeypot" aria-hidden="true"><label>Leave blank<input name="company_url" tabIndex={-1} autoComplete="off"/></label></div><p className="form-note">We’ll use these details to respond to your enquiry. Please don’t include sensitive information.</p>{!config.enquiryEndpoint && <p className="setup-notice">Enquiry form preview — online submission is awaiting configuration.</p>}<button type="submit" className="button" disabled={busy}>{busy ? 'Sending…' : 'Let’s Talk'}<ArrowUpRight size={18}/></button><p className="form-status" role="status">{status}</p></form>
}
function ContactSection() { return <section id="contact" className="section contact"><div className="container contact-grid"><div><Label>LET’S TALK GROWTH</Label><h2>Ready to turn your digital presence into a <em>growth engine?</em></h2><p className="large-copy">Tell us where your business is today, and where you want it to go.</p><div className="contact-detail"><span>BASED IN</span><strong>Mumbai, Maharashtra</strong></div>{config.email && <a className="contact-email" href={`mailto:${config.email}`}>{config.email}</a>}{config.phone && <a className="contact-email" href={`tel:${config.phone}`}>{config.phone}</a>}<WhatsApp/><p className="contact-small">A specific project or a long-term growth partner. Let’s find the right fit for your business.</p></div><ContactForm/></div></section> }
function Footer() { return <footer><div className="container"><div className="footer-grid"><div><Brand/><p>Revenue-Led Digital Transformation</p><span className="footer-tag">Strategy meets execution.<br/>Digital meets business growth.</span></div><div><h3>CAPABILITIES</h3>{['Digital Strategy', 'Website Development', 'E-commerce', 'Performance Marketing', 'Social Media Marketing', 'SEO', 'Digital Commerce', 'Business Automation'].map(x => <a key={x} href="#services">{x}</a>)}</div><div><h3>COMPANY</h3>{nav.filter(([x]) => x !== 'Home' && x !== 'Services').map(([x, id]) => <a key={id} href={`#${id}`}>{x}</a>)}</div><div><h3>LET’S CONNECT</h3><p>Mumbai, Maharashtra</p>{config.email ? <a href={`mailto:${config.email}`}>{config.email}</a> : <span className="pending-contact">Email & phone coming soon</span>}<a href="#contact">Start a conversation <ArrowUpRight size={14}/></a><span className="pending-contact">LinkedIn · Instagram · Facebook<br/>Official social links coming soon</span></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Chazon Digital Ventures</span><div><details><summary>Privacy Policy</summary><p>Enquiry details are used to respond to your request. No analytics integrations are enabled by default. A complete privacy policy, including retention and contact details, will be published before launch.</p></details><details><summary>Terms & Conditions</summary><p>This website introduces Chazon’s capabilities. Project scope, fees and deliverables are agreed separately in writing. Full website terms will be published before launch.</p></details></div><a href="#home">Back to top ↑</a></div></div></footer> }
export default function App() { return <><a className="skip-link" href="#main">Skip to content</a><Navbar/><main id="main"><Hero/><ProblemSection/><ValueProposition/><ServicePillars/><DifferenceSection/><ProcessSection/><AuditSection/><SelectedWork/><IndustriesSection/><WhyChazon/><FounderSection/><InsightsSection/><ContactSection/></main><Footer/><WhatsApp mobile/></> }
